Remove session middleware and simplify session handling code
oxidizing/sihl pull request #433
Opened 2021-03-14 16:46 UTC by jerben

@aronerben This is an approach without using middlewares. It simplifies quite a bit, what do you think?

2021-03-16 18:14 UTC, aronerben commented
> This is an approach without using middlewares. It simplifies quite a bit, what do you think?
> We could use the same approach for the `htmx` and maybe the `form` middlewares,

I'm a big fan, great refactor!

2021-03-16 18:40 UTC, jerben commented
Conflicts resolved

2021-03-16 19:05 UTC, aronerben approved these changes
Looks good!

2021-03-16 19:06 UTC, aronerben requested changes
Please check

2021-03-17 08:07 UTC, jerben commented on sihl/src/sihl.mli
> -    (** [session ?cookie_key ?secret ()] returns a middleware that reads and
I agree: https://oxidizing.github.io/sihl/sihl/index.html#limitations

2021-03-17 08:07 UTC, jerben commented on sihl/src/sihl.mli
> +      -> (string * string) list
Fixed

2021-03-17 08:08 UTC, jerben commented on sihl/src/sihl.mli
> +    val find
Fixed

2021-03-17 08:12 UTC, jerben commented
I also updated the documentation

2021-03-17 11:03 UTC, aronerben commented on sihl/src/sihl.mli
> -    (** [session ?cookie_key ?secret ()] returns a middleware that reads and
Ah :)

2021-03-17 11:03 UTC, aronerben commented on sihl/src/sihl.mli
> +    val find
Thanks

2021-03-17 11:04 UTC, aronerben commented on sihl/src/sihl.mli
> +      -> (string * string) list
Thanks

2021-03-17 11:04 UTC, aronerben approved these changes

2021-03-17 11:05 UTC, merged