Feature/complex collections UI with rest helpers
oxidizing/sihl pull request #476
Opened 2021-04-13 12:29 UTC by jerben

2021-04-15 16:37 UTC, jerben commented
Ready for review
Todo
- [ ] Make sure changlog reflects changes

2021-04-21 19:08 UTC, aronerben requested changes
Please check

2021-04-21 19:08 UTC, aronerben commented on sihl/src/sihl.mli
> +        by the user
Missing dot

2021-04-21 19:08 UTC, aronerben commented on sihl/src/sihl.mli
> +          [sort] is describes whether the result is sorted in descending or
Without "is"

2021-04-21 19:08 UTC, aronerben commented on sihl/src/web_rest.ml
> +    if limit + offset < total
Should it not be `<=` here?

2021-04-22 06:08 UTC, jerben commented on sihl/src/gen_repo.ml
> -let find_all_request =
Fixed.

2021-04-22 06:09 UTC, jerben commented on sihl/src/gen_repo.ml
> +         match type_ with
I didn't know you could do that, nice!

2021-04-22 06:10 UTC, jerben commented on sihl/src/gen_view.ml
> +    (query |> Sihl.Web.Rest.query_filter |> Option.value ~default:"")
Fixed.

2021-04-22 06:11 UTC, jerben commented on sihl/src/gen_view.ml
> +          (query |> Sihl.Web.Rest.query_filter |> Option.value ~default:"")
Fixed.

2021-04-22 06:17 UTC, jerben commented on sihl/src/gen_view.ml
> +<form style="display: inline;" action="/{{name}}s" method="Get">
They are indeed the same at the moment but the user probably wants to style them differently.

2021-04-22 06:18 UTC, jerben commented on sihl/src/sihl.mli
> +        by the user
Fixed.

2021-04-22 06:18 UTC, jerben commented on sihl/src/sihl.mli
> +          [sort] is describes whether the result is sorted in descending or
Fixed.

2021-04-22 06:20 UTC, jerben commented on sihl/src/web_rest.ml
> +    if limit + offset < total
You are right, fixed.

2021-04-25 13:31 UTC, aronerben commented on sihl/src/gen_repo.ml
> +         match type_ with
Yea OCaml seems to create equality for these kinds of data constructors.

2021-04-25 13:32 UTC, aronerben commented on sihl/src/gen_view.ml
> +<form style="display: inline;" action="/{{name}}s" method="Get">
Makes sense!

2021-04-25 13:33 UTC, merged