Add database helpers to run one caqti query
oxidizing/sihl pull request #490
Opened 2021-04-21 18:02 UTC by jerben

Fix #484

2021-04-25 13:16 UTC, aronerben requested changes

2021-04-25 13:16 UTC, aronerben commented on sihl/src/contract_database.ml
> +      Use {!exec} to run mutations. *)
Does `{!exec}` reference this function?

2021-04-25 13:16 UTC, aronerben commented on sihl/src/index.mld
> +If you need to run multiple caqti requests on the same connection, use {!val:Sihl.Database.query'}.
Shouldn't it be `query` without tick?

2021-04-25 13:16 UTC, aronerben commented on sihl/src/sihl.mli
> +      [None] if an unsupported database is used. [*)
Unnecessary `[` at the end

2021-04-26 10:55 UTC, jerben commented on sihl/src/contract_database.ml
> +      [None]. Returns [None] if no rows is found.
Fixed. It should highlight the difference to `find` which raises an error.

2021-04-26 10:55 UTC, jerben commented on sihl/src/contract_database.ml
> +      Note that the caqti request is allowed to return one, zero or many rows. *)
Yes because the caqti query contains this information in the type. If it doesn't compile, this explains why.

2021-04-26 10:55 UTC, jerben commented on sihl/src/contract_database.ml
> +      Use {!exec} to run mutations. *)
Yes

2021-04-26 10:57 UTC, jerben commented on sihl/src/index.mld
> +If you need to run multiple caqti requests on the same connection, use {!val:Sihl.Database.query'}.
You are right!

2021-04-26 10:57 UTC, jerben commented on sihl/src/index.mld
> +If you need to run multiple caqti requests on the same connection, use {!val:Sihl.Database.query'}.
Fixed.

2021-04-26 10:57 UTC, jerben commented on sihl/src/sihl.mli
> +      [None] if an unsupported database is used. [*)
Fixed.

2021-04-27 09:02 UTC, aronerben approved these changes

2021-04-27 09:02 UTC, aronerben commented
Please fix conflicts, after that you can merge

2021-04-27 09:55 UTC, jerben commented
Thanks! :slightly_smiling_face:

2021-04-27 10:37 UTC, aronerben commented
> Thanks!

There are conflicts again :grimacing:

2021-04-27 10:40 UTC, jerben commented
> There are conflicts again grimacing
Godangit, I am still dealing with the aftermath of the previous rebase :P

2021-04-27 11:01 UTC, merged